### ISSUE TITLE
Understand inspection regime

### ISSUE THREAD

**Issue by quantoidb** [cropmapteam/Scotland-crop-map#11]
Ground truth data:

Contact Rural Payments colleagues to understand inspection regime and dates ground truth data collected.

**Comment by chrissycoakley** [comment]
Email sent last week but no response yet (21/05/19)

**Comment by quantoidb** [comment]
Response From: Traill Alan 
Sent: 05 June 2019 11:49

Hi Chrissy 
Apologies for my late reply but I have been on leave and with my new pat-time working pattern it’s taken me while to get caught up.

I have attached a document that has all the Land Cover codes with descriptions (starting at page 36), also happy to have a discussion to help you better understand our data. In addition I would be more than happy to organise a farm visit to demonstrate our inspection procedures. We have a training farm at Newbridge that be perfect for such a visit.

I will try to give you a call to discuss further. Unfortunately we are still not in a position to extract all the 2018 inspection land covers from the new system and more annoyingly I can’t even give you a date when this functionality will be available but I will continue pursue this.

Alan Traill
GPS/GIS Systems Manager
Strathearn House
Perth PH1 1R
Tel: 07879608535

**Comment by quantoidb** [comment]
We are arranging the Newbridge Training Farm visit asap.

**Comment by quantoidb** [comment]
Richard and Beata met Alan Traill on 27 June 2019 at the Newbridge Learning Farm. We learned about farms inspection process. We also performed a practical exercise of walking and mapping the field using their training gear. A great day out, and a lot of learning. Thank you Alan!!
