### ISSUE TITLE
Get CROME code

### ISSUE THREAD

**Issue by quantoidb** [cropmapteam/Scotland-crop-map#12]
Request code from Sanjay for CROME methodology

**Comment by andrewhorne2** [comment]
Emailed Sanjay as per below, awaiting reply:

Sanjay,

  I’m leading a team at the University of Edinburgh who are working with the Scottish Government to provide a crop map survey like CROME based Sentinel-1 and -2 data for all of Scotland. We’ve read your extremely informative (and entertaining!) presentation on the use of machine learning at CROME, and are taking a similar approach.

  However we were naturally wondering if you and the RPA would be prepared to share more than just the same approach. We were intending, similar to you, of a Random Forest classification before moving onto a neural net if we have time. However if the RPA were happy to cooperate to the extent of an open-source based sharing of code, we would modify our approach to add to and extend CROME and feedback any improvements directly. Is this a possibility?

  May be worth mentioning that we believe there is a similar effort ongoing for Wales, who would I’m sure be interested in a shared effort.

  We’d be happy to speak to you, even if just to hear more of your experiences with the development of CROME. 

Thanks

Andrew

**Comment by quantoidb** [comment]
Sanjay presented CROME methodology in a team call on 22-May-2019. 
We will not be getting their dataset or code.
