### ISSUE TITLE
Plan analytical pipeline & packages

### ISSUE THREAD

**Issue by quantoidb** [cropmapteam/Scotland-crop-map#15]
Plan the analytical pipeline in order to decide which steps can be done in which package (R/Python/QGIS) and ensure compatibility

**Comment by StephenRESAS** [comment]
Andrew has been in touch with Sanjay from Rural Payments Agency. He's going to lead a session for us going through his data pipeline. We'll hopefully have a date in the calendar soon. He's also happy to be on the team in an advisory role going forward.

**Comment by quantoidb** [comment]
documented in #38
