### ISSUE TITLE
Get Ground Truth (INSPECTIONS) dataset

### ISSUE THREAD

**Issue by quantoidb** [cropmapteam/Scotland-crop-map#18]
Get Ground Truth dataset from INSPECTIONS team. 
This dataset covers 5% of all Scottish farms claiming CAP.

**Comment by spatial-scales** [comment]
Good news everyone! WE HAVE GROUND TRUTH DATA! It was surreptitiously handed to me in the corner of a barley field in Newbridge earlier today in the middle of a field survey in which I ended up taking GPS points in the middle of thistle bushes. The lengths I go to for this project...

**Comment by quantoidb** [comment]
Yeay!
