### ISSUE TITLE
Team VACATION schedule

### ISSUE THREAD

**Issue by quantoidb** [cropmapteam/Scotland-crop-map#19]
Team VACATION schedule. 

Please add your away dates as you plan them, so we are all aware of resource availability constraints. 
Thank you!

**Comment by quantoidb** [comment]
BEATA 
21-28 May 2019 - vacation 
3-5 May 2019 - in Glasgow for The Data Lab Innovation Week (MSc Hackathon) 
31 July 2019 - last day on the project

**Comment by Kostassan** [comment]
No planned vacations from now on.

**Comment by geojamesc** [comment]
JamesC

17th June - annual leave.
No further vacations planned yet.

**Comment by WilliamPetit** [comment]
WILLIAM
Annual Leave: from 21st June to 3rd of July

**Comment by andrewhorne2** [comment]
In Canada: 8th to 19th July

**Comment by spatial-scales** [comment]
I'm away 10th-12th of July, might be away another time in July but nothing confirmed yet.

**Comment by chrissycoakley** [comment]
Annual Leave: from 22nd July to end of project 
  Out of office - Thursday 20th (Royal Highland Show) and this coming Thursday 23rd May (but I'm going to do Crop mapping work on Tuesday instead)

**Comment by StephenRESAS** [comment]
Monday 2nd July to Thursday 5th July. A couple of other days dotted about perhaps but none planned for a Wednesday or Thursday yet.

**Comment by ZarPat** [comment]
Not available the week commencing 10th June. Start new job then.

**Comment by spatial-scales** [comment]
Will only be in on one day, Thursday 30th, next week.

**Comment by geojamesc** [comment]
I`m now taking 15th - 19th July off.
