### ISSUE TITLE
IT set up at Argyle House to allow VR machine for Kostas

### ISSUE THREAD

**Issue by quantoidb** [cropmapteam/Scotland-crop-map#21]
From: Beata 
Sent: 20 May 2019 12:17

Andrew, 
As out IT contact in Argyle House, I’ll let you run with the below request from Kostas  
Added Open Item to Github for tracking. 

Kostas, 
Can you please remind us what Orfeo is, and clarify what this VR will be used for? 

Thank you! 
Beata 

---------------------------------------------------- 
From: Kostas Sideris <Kostas.Sideris@jncc.gov.uk> 
Sent: 16 May 2019 12:17

Hi Beata

As you may have seen in my GitHub comment, I have had a meeting with Paul Gilbertson who worked with the Segmentation algorithm in Orfeo toolbox. 

He is very happy to use the package.
However, since this is a set up in a amazon WS virtual machine, I need to know the IT set up at Argyle house so I can let Paul know so he can ready for me the VR machine. 
After that we will be ready to feed it data and obtain the segmentation polygons.

Kostas

**Comment by Kostassan** [comment]
HI Beata,

Sorry for disappearing for a few days, (I was down with a rather nasty bit of the flu).  I have already e-mailed William with further info about this, but I will repost here.

Orfeo Toolbox is a set of packages for the processing of remote sensing images. It is based in a Python API and aC++ API. It can work as a QGIS set of tools but it had its own package so it can also work independently.  More info here: https://www.orfeo-toolbox.org/CookBook/

My colleague Paul Gilbertson has used the Segmentation algorithm in a Ubuntu system to produce a polygon shapefile, from satellite imagery.
A VR machine (from Amazon web services) was used and successfully produced polygons for all England.
The IT set up is needed so we can identify the needs of the VR machine. 
The final product of this will be one or multiple shapefiles of polygons that will have identified the land parcels that can be used to fill the crop map results data.

**Comment by StephenRESAS** [comment]
Hi Kostas, I've just met with the team at the Edinburgh Parallel Computing Centre (EPCC). They are building a virtual machine with a development area where we will be able to do the segmentation. It should be up and running by next week. I'll send you contact details for Elena at the EPCC, who will be setting it up for us from today. If you were able to put her in touch with your contact that would be great thanks.

Stephen

**Comment by Kostassan** [comment]
Hi Stephen

Thank you for this, I will put Paul Gilbertson in touch with her so he help her with the VR machine.

Kostas

Kostas Sideris
Environmental Data Specialist
JNCC, Inverdee House, Baxter Street, Torry, Aberdeen, AB11 9QA
Tel: 01224 266 561
Email: Kostas.Sideris@jncc.gov.uk<mailto:Kostas.Sideris@jncc.gov.uk>
[JNCC]
www.jncc.gov.uk<http://www.jncc.gov.uk/>
[facebook]<https://www.facebook.com/JNCCUK/>[twitter]<https://twitter.com/JNCC_UK>[linkdin]<https://www.linkedin.com/company/jncc/>25 years delivering innovative solutions to realise the value of nature.

**Comment by quantoidb** [comment]
VM setup, tested, Kostas using it as required.
