### ISSUE TITLE
Processing fields as individual files VS one large file

### ISSUE THREAD

**Issue by quantoidb** [cropmapteam/Scotland-crop-map#30]
William, James and Richard to meet to discuss processing fields as individual files or as one large file

**Comment by WilliamPetit** [comment]
I think we decide that we're going to process on the large file.
The work I've done individual file for each field canl be used for debugging as it will allow us to easily visualize a single field.
I've created a Issue for this work: #33

**Comment by quantoidb** [comment]
If a decision was made, please provide a quick update on status and close it :)

**Comment by WilliamPetit** [comment]
The process flow is now written down and we'll be using large file, individual file were not giving much performance advantage anyway. The work done to split fields as individual files is on github in case we want to use it later.
