### ISSUE TITLE
Check RFI masked images.

### ISSUE THREAD

**Issue by geojamesc** [cropmapteam/Scotland-crop-map#35]
Check that the output images that have been processed by the rasterio script to mask out the RFI locations are OK.

**Comment by geojamesc** [comment]
The 43 images which have so far been processed by the script, I have on my local machine. The total size for these 43 images is 211Gb. I`ll look at putting them somewhere or when you are in we can look at copying some or all of the images over to your SG laptop etc to check them out.

**Comment by geojamesc** [comment]
One of the images with the RFI regions masked out can be downloaded using this link:

https://uoe-my.sharepoint.com/:i:/g/personal/jcrone_ed_ac_uk/EXhBY9jW2a5DnUjJEMPNA04BlNDnqcZdcYSkmjZb7baFiA?e=TnCpsu

**Comment by geojamesc** [comment]
Re-ran the script rasterio mask out RFI regions using the corrected shapefiles. So there is now 47 S1 images which have had the tagged RFI regions masked out from them. I have these 47 images on my local machine. The total size of the 47 images is 231Gb.

**Comment by quantoidb** [comment]
Hi James, Do you need anyone else on the team to check these images? Are you waiting on anything to close this issue?

**Comment by geojamesc** [comment]
Nope. Issue closed.
