### ISSUE TITLE
Document data management workflow

### ISSUE THREAD

**Issue by quantoidb** [cropmapteam/Scotland-crop-map#38]
Document data management workflow.

**Comment by quantoidb** [comment]
High-level process attached. 
Next working on the details. 

[ScotCropMap_data_management_workflow-v1.pdf](https://github.com/cropmapteam/Scotland-crop-map/files/3359348/ScotCropMap_data_management_workflow-v1.pdf)

**Comment by quantoidb** [comment]
start of detailed workflow. 

[ScotCropMap_data_management_workflow-v2.pdf](https://github.com/cropmapteam/Scotland-crop-map/files/3359900/ScotCropMap_data_management_workflow-v2.pdf)

**Comment by quantoidb** [comment]
Completion pending review by the team.

**Comment by quantoidb** [comment]
[ScotCropMap_data_management_workflow-v3.pdf](https://github.com/cropmapteam/Scotland-crop-map/files/3363250/ScotCropMap_data_management_workflow-v3.pdf)

**Comment by geojamesc** [comment]
It should be EDINA rather than University of Edinburgh.
